export { default as block } from './block.js'
export { default as chainId } from './chainId.js'
export { default as ethereum } from './ethereum.js'
export { default as gtmnData } from './gtmnData.js'
export { default as p_gtmn } from './p_gtmn.js'
export { default as s_gtmn } from './s_gtmn.js'
export { default as gtmnBal } from './gtmnBal.js'
export { default as natvBal } from './natvBal.js'
// export { default as lp } from './lp.js'
// export { default as lpBal } from './lpBal.js'
export { default as provider } from './provider.js'
export { default as selectedAddress } from './selectedAddress.js'
export { default as signer } from './signer.js'